# Generated by Django 6.0.3 on 2026-04-17 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makola', '0004_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
