# Generated by Django 6.0.3 on 2026-06-25 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='description',
            field=models.TextField(blank=True, default='Payment for services rendered', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payee',
            field=models.CharField(default='Receiver', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer',
            field=models.CharField(default='Sender', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
