# Generated by Django 6.0.3 on 2026-06-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_description_payment_payee_payment_payer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(default='', editable=False, max_length=100, unique=True),
        ),
    ]
