# Generated by Django 6.0.3 on 2026-06-25 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reference',
        ),
    ]
