# Generated by Django 6.0.3 on 2026-03-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('LIFESTYLE', 'Lifestyle'), ('TRAVEL', 'Travel'), ('FOOD', 'Food')], default='TECHNOLOGY', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('LIFESTYLE', 'Lifestyle'), ('TRAVEL', 'Travel'), ('FOOD', 'Food')], default='TECHNOLOGY', max_length=20),
        ),
    ]
